#!/usr/bin/env python3
import ev3dev.ev3 as ev3
from time import sleep
# Playing game of Tic-Tac-Toe
# Defining motors and sensors
motor_right = ev3.LargeMotor('outD')
motor_left = ev3.LargeMotor('outA')
motor_medium =ev3.MediumMotor('outC')
ts = ev3.TouchSensor()
cl = ev3.ColorSensor()


# movement functions
def rotate_180_right():
    # move motor right for 180 deg rotation
    motor_right.run_timed(time_sp=4131.368955, speed_sp=-100, stop_action='hold')
    motor_left.run_timed(time_sp=4131.368955, speed_sp=100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    motor_right.wait_while('running')
    sleep(0.3)

def rotate_180_left():
    # move motor left for 180 deg rotation
    motor_right.run_timed(time_sp=4131.368955, speed_sp=100, stop_action='hold')
    motor_left.run_timed(time_sp=4131.368955, speed_sp=-100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    motor_right.wait_while('running')
    sleep(0.3)

def rotate_90_left():
    # move motor left for 90 deg rotation
    motor_right.run_timed(time_sp=4187.207128, speed_sp=100, stop_action='hold')
    # wait till the motor has stopped
    motor_right.wait_while('running')
    sleep(0.3)

def rotate_90_reverse_left():
    # move motor left for 90 deg rotation
    motor_right.run_timed(time_sp=4187.207128, speed_sp=-100, stop_action='hold')
    # wait till the motor has stopped
    motor_right.wait_while('running')
    sleep(0.3)

def rotate_90_right():
    # move motor right for 90 deg rotation
    motor_left.run_timed(time_sp=4187.207128, speed_sp=100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    sleep(0.3)

def rotate_90_reverse_right():
    # move motor right for 90 deg rotation
    motor_left.run_timed(time_sp=4187.207128, speed_sp=-100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    sleep(0.3)

def rotate_90_left_alt():
    # move motor left for 90 deg rotation
    motor_right.run_timed(time_sp=2065.684478, speed_sp=100, stop_action='hold')
    motor_left.run_timed(time_sp=2065.684478, speed_sp=-100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    motor_right.wait_while('running')
    sleep(0.3)

def rotate_90_right_alt():
# move motor right for 90 deg rotation
    motor_right.run_timed(time_sp=2065.684478, speed_sp=-100, stop_action='hold')
    motor_left.run_timed(time_sp=2065.684478, speed_sp=100, stop_action='hold')
    # wait till the motor has stopped
    motor_left.wait_while('running')
    motor_right.wait_while('running')
    sleep(0.3)

def striaght_to_adj():
    motor_left.run_to_rel_pos(position_sp=442.5365854, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=442.5365854, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_to_adj():
    motor_left.run_to_rel_pos(position_sp=-442.5365854, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-442.5365854, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def straight_1_adj():
    motor_left.run_to_rel_pos(position_sp=332, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=332, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def straight_1_middle():
    motor_left.run_to_rel_pos(position_sp=480, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=480, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_1_adj():
    motor_left.run_to_rel_pos(position_sp=-332, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-332, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_1_middle():
    motor_left.run_to_rel_pos(position_sp=-480, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-480, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(10)


def straight_2_adj():
    motor_left.run_to_rel_pos(position_sp=619.0243903, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=619.0243903, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def straight_2_middle():
    motor_left.run_to_rel_pos(position_sp=807.8048781, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=807.8048781, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(10)

def reverse_2_adj():
    motor_left.run_to_rel_pos(position_sp=-619.0243903, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-619.0243903, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_2_middle():
    motor_left.run_to_rel_pos(position_sp=-807.8048781, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-807.8048781, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(10)

def straight_3_adj():
    motor_left.run_to_rel_pos(position_sp=906.0487805, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=906.0487805, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def straight_3_middle():
    motor_left.run_to_rel_pos(position_sp=1135.609756, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=1135.609756, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_3_adj():
    motor_left.run_to_rel_pos(position_sp=-906.0487805, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-906.0487805, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def reverse_3_middle():
    motor_left.run_to_rel_pos(position_sp=-1135.609756, speed_sp=100, stop_action='hold')
    motor_right.run_to_rel_pos(position_sp=-1135.609756, speed_sp=100, stop_action='hold')
    motor_right.wait_while('running')
    motor_left.wait_while('running')
    sleep(0.3)

def grab():
    # grab action
    motor_medium.run_timed(time_sp=3500, speed_sp=-1000, stop_action="brake")
    motor_medium.wait_while('running')
    sleep(0.1)

def release():
    # release action
    motor_medium.run_timed(time_sp=3500, speed_sp=1000, stop_action="brake")
    motor_medium.wait_while('running')
    sleep(10)


def space1():
    #put block on 1
    rotate_180_right()
    grab()
    rotate_180_left()
    rotate_90_left_alt()
    striaght_to_adj()
    rotate_90_right()
    straight_3_adj()
    rotate_90_right()
    release()
    rotate_90_reverse_right()
    reverse_3_adj()
    rotate_90_reverse_right()
    reverse_to_adj()
    rotate_90_right_alt()
    sleep(30) #sleep for next colour detection

def space4():
    #put block on 2
    
